arm_left_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - arm_left_joint_1_s
    - arm_left_joint_2_l
    - arm_left_joint_3_e
    - arm_left_joint_4_u
    - arm_left_joint_5_r
    - arm_left_joint_6_b
    - arm_left_joint_7_t
  gains:
    arm_left_joint_1_s:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_left_joint_2_l:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_left_joint_3_e:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_left_joint_4_u:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_left_joint_5_r:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_left_joint_6_b:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_left_joint_7_t:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
arm_right_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - arm_right_joint_1_s
    - arm_right_joint_2_l
    - arm_right_joint_3_e
    - arm_right_joint_4_u
    - arm_right_joint_5_r
    - arm_right_joint_6_b
    - arm_right_joint_7_t
  gains:
    arm_right_joint_1_s:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_right_joint_2_l:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_right_joint_3_e:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_right_joint_4_u:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_right_joint_5_r:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_right_joint_6_b:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_right_joint_7_t:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
arms_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - arm_left_joint_1_s
    - arm_left_joint_2_l
    - arm_left_joint_3_e
    - arm_left_joint_4_u
    - arm_left_joint_5_r
    - arm_left_joint_6_b
    - arm_left_joint_7_t
    - arm_right_joint_1_s
    - arm_right_joint_2_l
    - arm_right_joint_3_e
    - arm_right_joint_4_u
    - arm_right_joint_5_r
    - arm_right_joint_6_b
    - arm_right_joint_7_t
  gains:
    arm_left_joint_1_s:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_left_joint_2_l:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_left_joint_3_e:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_left_joint_4_u:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_left_joint_5_r:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_left_joint_6_b:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_left_joint_7_t:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_right_joint_1_s:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_right_joint_2_l:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_right_joint_3_e:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_right_joint_4_u:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_right_joint_5_r:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_right_joint_6_b:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_right_joint_7_t:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
torso_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - torso_joint_b1
  gains:
    torso_joint_b1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
sda10f_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - torso_joint_b1
    - arm_left_joint_1_s
    - arm_left_joint_2_l
    - arm_left_joint_3_e
    - arm_left_joint_4_u
    - arm_left_joint_5_r
    - arm_left_joint_6_b
    - arm_left_joint_7_t
    - arm_right_joint_1_s
    - arm_right_joint_2_l
    - arm_right_joint_3_e
    - arm_right_joint_4_u
    - arm_right_joint_5_r
    - arm_right_joint_6_b
    - arm_right_joint_7_t
  gains:
    torso_joint_b1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_left_joint_1_s:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_left_joint_2_l:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_left_joint_3_e:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_left_joint_4_u:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_left_joint_5_r:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_left_joint_6_b:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_left_joint_7_t:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_right_joint_1_s:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_right_joint_2_l:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_right_joint_3_e:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_right_joint_4_u:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_right_joint_5_r:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_right_joint_6_b:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_right_joint_7_t:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
left_arm_plus_torso_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - torso_joint_b1
    - arm_left_joint_1_s
    - arm_left_joint_2_l
    - arm_left_joint_3_e
    - arm_left_joint_4_u
    - arm_left_joint_5_r
    - arm_left_joint_6_b
    - arm_left_joint_7_t
  gains:
    torso_joint_b1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_left_joint_1_s:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_left_joint_2_l:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_left_joint_3_e:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_left_joint_4_u:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_left_joint_5_r:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_left_joint_6_b:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_left_joint_7_t:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
right_arm_plus_torso_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - torso_joint_b1
    - arm_right_joint_1_s
    - arm_right_joint_2_l
    - arm_right_joint_3_e
    - arm_right_joint_4_u
    - arm_right_joint_5_r
    - arm_right_joint_6_b
    - arm_right_joint_7_t
  gains:
    torso_joint_b1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_right_joint_1_s:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_right_joint_2_l:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_right_joint_3_e:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_right_joint_4_u:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_right_joint_5_r:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_right_joint_6_b:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_right_joint_7_t:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
