controller_list:
  - name: arm_left_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - arm_left_joint_1_s
      - arm_left_joint_2_l
      - arm_left_joint_3_e
      - arm_left_joint_4_u
      - arm_left_joint_5_r
      - arm_left_joint_6_b
      - arm_left_joint_7_t
  - name: arm_right_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - arm_right_joint_1_s
      - arm_right_joint_2_l
      - arm_right_joint_3_e
      - arm_right_joint_4_u
      - arm_right_joint_5_r
      - arm_right_joint_6_b
      - arm_right_joint_7_t
  - name: torso_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - torso_joint_b1
  - name: arms_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - arm_left_joint_1_s
      - arm_left_joint_2_l
      - arm_left_joint_3_e
      - arm_left_joint_4_u
      - arm_left_joint_5_r
      - arm_left_joint_6_b
      - arm_left_joint_7_t
      - arm_right_joint_1_s
      - arm_right_joint_2_l
      - arm_right_joint_3_e
      - arm_right_joint_4_u
      - arm_right_joint_5_r
      - arm_right_joint_6_b
      - arm_right_joint_7_t
  - name: sda10f_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - torso_joint_b1
      - arm_left_joint_1_s
      - arm_left_joint_2_l
      - arm_left_joint_3_e
      - arm_left_joint_4_u
      - arm_left_joint_5_r
      - arm_left_joint_6_b
      - arm_left_joint_7_t
      - arm_right_joint_1_s
      - arm_right_joint_2_l
      - arm_right_joint_3_e
      - arm_right_joint_4_u
      - arm_right_joint_5_r
      - arm_right_joint_6_b
      - arm_right_joint_7_t